- include: asg_ec2.yaml
  when: ec2_load_balancer is not defined

- include: asg_elb.yaml
  when: ec2_load_balancer is defined

# Create AutoScaling Policies
# Scale down
- name: Updating AutoScaling Policies
  ec2_scaling_policy:
    state: "{{ state | default('present') }}"
    region: "{{ region }}"
    name: "{{ aws_asg.name }}-ScaleDown Policy"
    adjustment_type: "ChangeInCapacity"
    asg_name: "{{ aws_asg.name }}"
    scaling_adjustment: "{{ aws_asg_scaledown_adjustment | default('-1')  }}"
    min_adjustment_step: 1
    cooldown: "{{ cooldown | default(300) }}"
  register: aws_asg_scaledown

# Scale up
- ec2_scaling_policy:
    state: "{{ state | default('present') }}"
    region: "{{ region }}"
    name: "{{ aws_asg.name }}-ScaleUp Policy"
    adjustment_type: "ChangeInCapacity"
    asg_name: "{{ aws_asg.name }}"
    scaling_adjustment: "{{ aws_asg_scaleup_adjustment | default('+1') }}"
    min_adjustment_step: 1
    cooldown: "{{ cooldown | default(300) }}"
  register: aws_asg_scaleup

# Create LOW CloudWatch Alarms for the AS Group
# http://docs.ansible.com/ansible/ec2_metric_alarm_module.html
- name: Update EC2 Low Metric Alarms
  ec2_metric_alarm:
    state: "{{ state | default('present') }}"
    region: "{{ region }}"
    name: "{{ ec2_metric_alarm_metric_low_name }}"
    metric: "{{ ec2_metric_alarm_low_metric }}"
    namespace: "{{ ec2_metric_alarm_low_namespace }}"
    statistic: "{{ ec2_metric_alarm_low_statistic }}"
    comparison: "{{ ec2_metric_alarm_low_operator }}"
    threshold: "{{ ec2_metric_alarm_low_trigger }}"
    period: "{{ ec2_metric_alarm_low_interval }}"
    evaluation_periods: "{{ ec2_metric_alarm_low_evaluation_periods }}"
    unit: "{{ ec2_metric_alarm_low_unit }}"
    description: "{{ ec2_metric_alarm_low_description }}"
    dimensions: "{{ ec2_metric_alarm_low_dimensions }}"
    alarm_actions: ["{{ aws_asg_scaledown.arn }}"]
  register: asg_cw_low
  tags: asg_cw_low

# Create HIGH CloudWatch Alarms for the AS Group
- name: Update EC2 high Metric Alarms
  ec2_metric_alarm:
    state: "{{ state | default('present') }}"
    region: "{{ region }}"
    name: "{{ ec2_metric_alarm_metric_high_name }}"
    metric: "{{ ec2_metric_alarm_high_metric }}"
    namespace: "{{ ec2_metric_alarm_high_namespace }}"
    statistic: "{{ ec2_metric_alarm_high_statistic }}"
    comparison: "{{ ec2_metric_alarm_high_operator }}"
    threshold: "{{ ec2_metric_alarm_high_trigger }}"
    period: "{{ ec2_metric_alarm_high_interval }}"
    evaluation_periods: "{{ ec2_metric_alarm_high_evaluation_periods }}"
    unit: "{{ ec2_metric_alarm_high_unit }}"
    description: "{{ ec2_metric_alarm_high_description }}"
    dimensions: "{{ ec2_metric_alarm_high_dimensions }}"
    alarm_actions: ["{{ aws_asg_scaleup.arn }}"]
  register: asg_cw_high
  tags: asg_cw_high
