- name: terminate  asg
  ec2_asg:
    name: "{{ vivareal_project_build }}"
    state: absent
    region: "{{ region }}"
  register: result

- name: terminate launch_config
  ec2_lc:
    name: "{{ result.launch_config_name }}"
    region: "{{ region }}"
    state: absent