---
# tasks file for aws-asg
- fail: msg="The minimum Ansible version required to run is 2.0.1. To upgrade run 'sudo pip install --upgrade ansible'."
  when: ansible_version.major|int != 2 and ansible_version.minor|int < 0 and ansible_version.revision|int < 1

- include: asg.yml
- include: lifecycle-hook.yml
  when: aws_resource_tags.zabbix_metadata is defined
- include: terminate_relative.yml
  when: relative is defined and terminate_relative is defined and terminate_relative|bool == True