---
# tasks file for aws-asg
- fail: msg="The minimum Ansible version required to run is 2.0.1. To upgrade run 'sudo pip install --upgrade ansible'."
  when: ansible_version.major|int != 2 and ansible_version.minor|int < 0 and ansible_version.revision|int < 1

- include: asg.yml
  when: (state is defined and not state == "absent") or state is not defined

- include: lifecycle-hook.yml
  when: aws_resource_tags.zabbix_metadata is defined and (state is not defined or state == "present")

- include: destroy.yml
  when: state is defined and state == "absent"